version: 2
jobs:
  build:
    docker:
      - image: node:8.4

    working_directory: ~/repo
    steps:
      - checkout

      # Restore npm cache
      - type: cache-restore
        key: npm-{{ checksum "package-lock.json" }}

      - run:
          name: npm setup
          command: |
            npm config set user 0
            npm config set unsafe-perm true
            npm install -g hexo-cli
            npm install -D netlify-cli

      - run: npm install

       # Store npm cache
      - type: cache-save
        key: npm-{{ checksum "package-lock.json" }}
        paths:
          - ~/repo

      - run:
          name: build public file
          command: |
            hexo g
            ls public/

      - deploy:
          name: Hosting Netlify
          command: |
            if [ "${CIRCLE_BRANCH}" == "feature/netlify" ]; then
              ./node_modules/netlify-cli/bin/cli.js deploy \
              -p public/
              --site-id ${MASTER_SITE_ID} \
              --access-token ${NETLIFY_TOKEN}
            else
              echo "Not master branch so not deploying"
            fi