version: 2
jobs:
  build:
    docker:
      - image: node:8.4

    working_directory: ~/repo
    steps:
      - run:
          name: Check Github connection
          command: echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc

      - run:
          name: Checkout Git repo
          command: |
            repository_https_url=$(echo $CIRCLE_REPOSITORY_URL | sed -e "s|git@github.com:|https://github.com/|")
            echo $repository_https_url
            git clone --branch $CIRCLE_BRANCH --single-branch $repository_https_url .

      - run:
          name: Setup build tools
          command: |
            npm config set user 0
            npm config set unsafe-perm true
            npm install -g hexo-cli
            npm install -g netlify-cli

      - run: npm install

      - run:
          name: Build public files
          command: |
            git log -n 2
            cat source/_posts/test-writing.md
            hexo generate

      - deploy:
          name: Hosting Netlify
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo \{\"site_id\":\"${MASTER_SITE_ID}\",\"path\":\"public\"\} >> .netlify
            else
              echo "Not master branch so not deploying"
            fi