version: 2
jobs:
  build:
    docker:
      - image: node:8.4

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Setup build tools
          command: |
            npm config set user 0
            npm config set unsafe-perm true
            npm install -g hexo-cli
            npm install -g netlify-cli

      - run: npm install

      - run:
          name: Build public files
          command: |
            hexo generate

      - deploy:
          name: Hosting Netlify
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo \{\"site_id\":\"${MASTER_SITE_ID}\",\"path\":\"public\"\} >> .netlify
              /usr/local/lib/node_modules/netlify-cli/bin/cli.js deploy -t ${NETLIFY_TOKEN}
            else
              echo "Not master branch so not deploying"
            fi