version: 2
jobs:
  build:
    docker:
      - image: node:8.4

    working_directory: ~/repo
    steps:
      - run:
          name: GitHubへのHTTPS接続の認証設定
          command: echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
      - run:
          name: GitリポジトリのCheckout
          command: |
            repository_https_url=$(echo $CIRCLE_REPOSITORY_URL | sed -e "s|git@github.com:|https://github.com/|")
            git clone --depth=1 --branch $CIRCLE_BRANCH --single-branch $repository_https_url .
            git reset --hard $CIRCLE_SHA1 || (echo "ビルド実行後にブランチが更新されました。Rebuildしてください。" 1>&2; false)
            git log -n 5

      - type: cache-restore
        key: npm-{{ checksum "package-lock.json" }}

      - run:
          name: npm setup
          command: |
            npm config set user 0
            npm config set unsafe-perm true
            npm install -g hexo-cli
            npm install -g netlify-cli

      - run: npm install

      - type: cache-save
        key: npm-{{ checksum "package-lock.json" }}
        paths:
          - ~/repo

      - run:
          name: build public files
          command: |
            hexo generate
            cat public/index.html

      - deploy:
          name: Hosting Netlify
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo \{\"site_id\":\"${MASTER_SITE_ID}\",\"path\":\"public\"\} >> .netlify
              /usr/local/lib/node_modules/netlify-cli/bin/cli.js deploy -t ${NETLIFY_TOKEN}
            else
              echo "Not master branch so not deploying"
            fi