version: 2
jobs:
  build:
    docker:
      - image: node:8.4

    working_directory: ~/repo
    steps:
      - run:
          name: Check Github connection
          command: echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc

      - run:
          name: Checkout Git repo
          command: |
            repository_https_url=$(echo $CIRCLE_REPOSITORY_URL | sed -e "s|git@github.com:|https://github.com/|")
            git clone --branch $CIRCLE_BRANCH --single-branch $repository_https_url .
            git log -n 1

      - type: cache-restore
        key: npm-{{ checksum "package-lock.json" }}

      - run:
          name: Setup build tools
          command: |
            npm config set user 0
            npm config set unsafe-perm true
            npm install -g hexo-cli
            npm install -g netlify-cli

      - run: npm install

      - type: cache-save
        key: npm-{{ checksum "package-lock.json" }}
        paths:
          - ~/repo

      - run:
          name: Build public files
          command: |
            hexo generate

      - deploy:
          name: Hosting Netlify
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo \{\"site_id\":\"${MASTER_SITE_ID}\",\"path\":\"public\"\} >> .netlify
              /usr/local/lib/node_modules/netlify-cli/bin/cli.js deploy -t ${NETLIFY_TOKEN}
            else
              echo "Not master branch so not deploying"
            fi